In [4]:
from scipy.sparse import coo_array, coo_matrix
import numpy as np

A = coo_array((10, 10), dtype=np.float32)
B = coo_matrix((10, 10), dtype=np.float32)

In [6]:
A[1,0]=5


TypeError: 'coo_array' object does not support item assignment

In [14]:
from ComputeTransitionProbabilities import compute_transition_probabilities, compute_transition_probabilities_sparse
from Constants import Constants

P=compute_transition_probabilities(Constants)
shape=P.shape
size_P=shape[0]*shape[1]*shape[2]
print(shape)
print(len(P.nonzero()))

print(f"Percent nonzero: {len(P.nonzero())/size_P}")

(1944, 1944, 3)
3
Percent nonzero: 2.646107470067232e-07


In [15]:
P = compute_transition_probabilities_sparse(Constants)
print(P)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
