In [4]:
from scipy.sparse import coo_array, coo_matrix
import numpy as np

A = coo_array((10, 10), dtype=np.float32)
B = coo_matrix((10, 10), dtype=np.float32)

In [6]:
A[1,0]=5


TypeError: 'coo_array' object does not support item assignment

In [2]:
from ComputeTransitionProbabilities import (
    compute_transition_probabilities,
    compute_transition_probabilities_sparse,
)
from Constants import Constants

P = compute_transition_probabilities(Constants)
shape = P.shape
size_P = shape[0] * shape[1] * shape[2]


print(f"Percent nonzero: {np.count_nonzero(P)/size_P}")

Percent nonzero: 0.002972107910379515


In [5]:
from ComputeStageCosts import (
    compute_stage_cost
)
from Constants import Constants
import numpy as np

G=compute_stage_cost(Constants)


shape = G.shape
size_P = shape[0] * shape[1]


print(f"Percent nonzero: {np.count_nonzero(G)/size_P}")

(1944, 3)
2
Percent nonzero: 1.0


In [7]:
import numpy as np

P = compute_transition_probabilities_sparse(Constants)
P_down = P[0]
K = Constants.T * Constants.D * Constants.N * Constants.M
test_mat = np.ones(shape=(K, K))
test_vec = np.ones(K)
print(P_down.dot(test_mat))
print(P_down.dot(test_vec))
# for j in range(100):
#     for i in range(K):
#         P_down.getrow(i).dot(test_mat)

for j in range(100):
    for i in range(K):
        P_down.getcol(i).transpose().dot(test_mat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[0. 0. 0. ... 1. 1. 1.]


C:\Users\patri\AppData\Local\Temp\ipykernel_21284\333553966.py:16: DeprecationWarning: `getcol` is deprecated and will be removed in v1.13.0; use `X[:, [0]]` instead.
  P_down.getcol(i).transpose().dot(test_mat)
C:\Users\patri\AppData\Local\Temp\ipykernel_21284\333553966.py:16: DeprecationWarning: `getcol` is deprecated and will be removed in v1.13.0; use `X[:, [1]]` instead.
  P_down.getcol(i).transpose().dot(test_mat)
C:\Users\patri\AppData\Local\Temp\ipykernel_21284\333553966.py:16: DeprecationWarning: `getcol` is deprecated and will be removed in v1.13.0; use `X[:, [2]]` instead.
  P_down.getcol(i).transpose().dot(test_mat)
C:\Users\patri\AppData\Local\Temp\ipykernel_21284\333553966.py:16: DeprecationWarning: `getcol` is deprecated and will be removed in v1.13.0; use `X[:, [3]]` instead.
  P_down.getcol(i).transpose().dot(test_mat)
C:\Users\patri\AppData\Local\Temp\ipykernel_21284\333553966.py:16: DeprecationWarning: `getcol` is deprecated and will be removed in v1.13.0; use `X[:, 